language: python
python:
   - "3.6"

addons:
  postgresql: "9.4"
services:
   - postgresql
  
install:
   - pip install -r requirements.txt
  
before_script:
    - psql -c 'create database food_delivery;' -U postgres
script:
    - pytest --cov=src --cov-config src/tests/tests.py

after_success:
    - coveralls
notifications:
  email: false
