language: python
dist: bionic
python:
   - "3.6"

addons:
  postgresql: "9.4"
services:
   - postgresql
  
install:
   - pip install pipenv
   - pipenv install
   - pip install -r requirements.txt
  
before_script:
    - psql -c 'create database food_delivery;'
script:
    pytest --cov --cov-config

after_success:
    - coveralls

