language: python
python:
   - "3.6"

addons:
  postgresql: "9.4"
services:
   - postgresql
  
install:
   - pip install pipenv
   - pipenv install
  
before_script:
    - psql -c 'create database food_delivery;' -U postgres
script:
    pytest --cov=src --cov-config .coveragerc

after_success:
    - coveralls

